/// Flutter icons LogeMoi_icon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LogeMoi_icon
///      fonts:
///       - asset: fonts/LogeMoi_icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LogeMoi_icon {
  LogeMoi_icon._();

  static const _kFontFam = 'LogeMoi_icon';
  static const _kFontPkg = null;

  static const IconData logo_loge_moi_01 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
